
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.node.maintain
  resources:
  - nodemaintains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.node.maintain
  resources:
  - nodemaintains/finalizers
  verbs:
  - update
- apiGroups:
  - batch.node.maintain
  resources:
  - nodemaintains/status
  verbs:
  - get
  - patch
  - update
